version: '3'
services:
  nsqlookupd:      # 有点像zookeeper 监控服务可用性
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"   # nsq 服务检测
      - "4161:4161"   # nsq admin 服务检测
  nsqd:
    image: nsqio/nsq   # nsq core
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"      # 服务端口
  nsqadmin:         # 可视化管理界面
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"      #  web